package android.todo.com.database;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import android.todo.com.database.TodoTask;

import android.todo.com.database.TodoTaskDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig todoTaskDaoConfig;

    private final TodoTaskDao todoTaskDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        todoTaskDaoConfig = daoConfigMap.get(TodoTaskDao.class).clone();
        todoTaskDaoConfig.initIdentityScope(type);

        todoTaskDao = new TodoTaskDao(todoTaskDaoConfig, this);

        registerDao(TodoTask.class, todoTaskDao);
    }
    
    public void clear() {
        todoTaskDaoConfig.getIdentityScope().clear();
    }

    public TodoTaskDao getTodoTaskDao() {
        return todoTaskDao;
    }

}
