package android.todo.com.database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import android.os.Parcel;
import android.os.Parcelable;

/**
 * Entity mapped to table "TODO_TASK".
 */
public class TodoTask implements Parcelable {

    private Long _id;
    private String title;
    private String description;
    private String created_date;

    public TodoTask() {
    }

    public TodoTask(Long _id) {
        this._id = _id;
    }

    public TodoTask(Long _id, String title, String description, String created_date) {
        this._id = _id;
        this.title = title;
        this.description = description;
        this.created_date = created_date;
    }

    protected TodoTask(Parcel in) {
        title = in.readString();
        description = in.readString();
        created_date = in.readString();
    }

    public static final Creator<TodoTask> CREATOR = new Creator<TodoTask>() {
        @Override
        public TodoTask createFromParcel(Parcel in) {
            return new TodoTask(in);
        }

        @Override
        public TodoTask[] newArray(int size) {
            return new TodoTask[size];
        }
    };

    public Long get_id() {
        return _id;
    }

    public void set_id(Long _id) {
        this._id = _id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getCreated_date() {
        return created_date;
    }

    public void setCreated_date(String created_date) {
        this.created_date = created_date;
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeString(title);
        dest.writeString(description);
        dest.writeString(created_date);
    }

    public boolean contains(String query) {
        if (title.contains(query) || description.contains(query)) {
            return true;
        } else return false;
    }

}
